### ISSUE TITLE
Can you please provide the minified version of the library?

### ISSUE THREAD

**Issue by gulsahkandemir** [Ciul/angular-facebook#100]
We use this library in our web app and it would be perfect if the minified version is also provided in the repo.

**Comment by purdel** [comment]
Use UglifyJS

**Comment by Ciul** [comment]
Ask @mrzmyr to add you as a collaborator and you could provide us with ith :D
Open source matters :100: %

Regards

**Comment by mrzmyr** [comment]
#113, there you go :shipit:
