### ISSUE TITLE
Chrome popup blocker results in blank page

### ISSUE THREAD

**Issue by ArminVieweg** [Ciul/angular-facebook#101]
Hi, I am using your lib for Angular and it works almost always. Just in case, that Chrome blocks the popup window, the login does not work anymore and results in a blank page.

I've tested this behaviour in three browsers: IE, Firefox and Chrome.

**IE** shows a message, that a popup tries to open and you need to accept it. After clicking, the page reloads and now the popup opens. After successful login to FB the popup is closing and the auth was successful.

In **Firefox** at address bar the hint for the popup appears. Clicking there to show the popup shows the popup. After the login to facebook, the auth was successful, but the popup (blank) still stays there, and does not close automatically, as in IE.

Now, in **Chrome** also at address bar a hint appears. Clicking there also shows the popup. But after login to FB nothing happens anymore. The "blank popup" is not completely blank. It contains a postMessage to a window which seems not to exist anymore.

This is the content of blank popup:

```js
var message = "....", // stripped the message for this issue
    origin = "http:\/\/interface.domain.com",
    domain = "interface.domain.com";
document.domain = 'facebook.com';
(function() {
    var a = window.opener || window.parent,
        b = 'fb_xdm_frame_' + location.protocol.replace(':', '');

    function c() {
        try {
            a.frames[b].proxyMessage(message, origin);
        } catch (e) {
            setTimeout(c, 100);
        }
    }

    function d() {
        __fbNative.postMessage(message, origin);
    }
    if (window == top && /FBAN\/\w+;/i.test(navigator.userAgent)) {
        if (window.__fbNative && __fbNative.postMessage) {
            d();
        } else window.addEventListener('fbNativeReady', d);
    } else c();
})();
```

This "error" appears just if popup blocker takes effect. If you allow popups for the current page (or disable popup blocker completely) it works.

In console no messages appear (even with set "preserve log").

Hope you have an idea why this happen. Thanks in advance.

**Comment by Ciul** [comment]
Hi Armin,

my first guess is that you are calling the login method directly by code without an user interaction, e.g. a button click. If that's the case then yes, it is supposed to happen that way (pop-up blocker taking effect).

As far as I know, pop-ups aren't blocked just if they happens due to an user interaction, in most cases, a click on a button. Thus, I would suggest you to add a directive ng-click to a button which triggers the login method/logic in your controller.

Hope that helps :]

**Comment by ArminVieweg** [comment]
Hi Ciul,

I am calling the login method this way in controller:

```js
$scope.facebookLogin = function() {
	FacebookService.login(function(facebookResponse) {
		facebookResponse['_provider'] = 'facebook';
		window.parent.postMessage(angular.toJson(facebookResponse), '*');
	});
};
```

The button looks like this:
```html
<button type="button" class="btn btn-full btn-blue mb-lg" ng-click="facebookLogin()">
	<i class="icon icon-facebook"></i>
	<span>Login with Facebook</span>
</button>
```

I guess that all interactions via directives (like ng-click) are not registred by chrome as user interaction.

**Comment by ArminVieweg** [comment]
I should mention that I am calling your lib not directly. I've built a FacebookService:

```js
'use strict';
angular.module('xxx').service('FacebookService', ['Facebook', function(Facebook) {

	var permissions = 'email,public_profile,user_friends';

	/**
	 * Api call to facebook
	 *
	 * @param {function} callback
	 */
	var apiCall = function(callback) {
		Facebook.api('/me', function(facebookResponse) {
			callback(facebookResponse);
		});
	};

	/**
	 * Set requested Facebook permissions.
	 * Default is 'email,public_profile,user_friends'
	 *
	 * @param {string} requestedPermissions
	 */
	this.setRequestedPermissions = function(requestedPermissions) {
		permissions = requestedPermissions;
	};

	/**
	 * Facebook Login
	 *
	 * @param {function} callback
	 * @param {string} permissions
	 */
	this.login = function(callback) {
		Facebook.getLoginStatus(function(response) {
			if (response.status === 'connected') {
				apiCall(callback);
			} else {
				Facebook.login(function(response) {
					if (response.authResponse) {
						apiCall(callback);
					}
				}, {scope: permissions});
			}
		});
	};
}]);
```

So the login method I am calling in button is the FacebookService's one.

**Comment by Ciul** [comment]
So maybe that's the cause. As I said, if the event is not called directly by an user interaction, pop-up windows will be blocked. In this case, the login method is being called lately in another moment by a third, your service who calls the getLoginStatus who calls the final login method.
Such a long chain! :P

I bet that login method sould be called without so much intermediaries.
Give it a try and come back if need more help :]

Hope that helps!

**Comment by ArminVieweg** [comment]
I will try and keep you up to date. But I don't see the difference. In your readme.md you recommend using a scope function which calls your login method. When pressing the button a ng-click will call the scope function, which calls your method then. So this is also chaining and, in my opinion, far away from "directly user interaction".

But I will try! Thanks so far.

**Comment by ArminVieweg** [comment]
Wow. You were totally right! This confuses me, but it works, without popup blocker warning. Thanks a lot :)

**Comment by Ciul** [comment]
Nice to know.

Now, let's clarify because I don't like you been confused. I prefer people learn and understand.

In your implementation, the final login call was inside the getLoginStatus, and this is asynchronous. So, the login method was been called in another instance of time not related to the user interaction.

In the readme examples, the login method at the scope is been called directly from the user interaction and calling right away the login function of the plugin. That's the difference.

Hope that helps :]

**Comment by ArminVieweg** [comment]
Yeah, okay. The async thing was probably the reason. My final scope function looks like this, now:

```js
$scope.login = function() {
	Facebook.login(function(response) {
		if (response.authResponse) {
			Facebook.api('/me', function(facebookResponse) {
				facebookResponse['_provider'] = 'facebook';
				window.parent.postMessage(angular.toJson(facebookResponse), '*');
			});
		}
	}, {scope: 'email,public_profile,user_friends'});
};
```
This `scope: 'email,public_profile,user_friends'` thing was necessary in order to get all infos of the user correctly. I had the issue that sometimes the mail address wasn't delivered by Facebook. Setting the scope helped.

However, you helped me a lot! Now it works perfectly.
