### ISSUE TITLE
npm

### ISSUE THREAD

**Issue by Zertz** [Ciul/angular-facebook#109]
I took the liberty of publishing the module on npm. I simply cloned your repo as is.

https://www.npmjs.com/package/angularjs-facebook

@Ciul let me know what your username is on npm and I'll give you ownership

**Comment by Ciul** [comment]
Hi Zertz, thank you for that.

It's okay as it is. I prefer you keep it so you give it support.
Each help helps! Remember that a lot of water drops make oceans :)

**Comment by mrzmyr** [comment]
:+1: :ocean:
