### ISSUE TITLE
Permissions for angular-facebook

### ISSUE THREAD

**Issue by alonshoshani** [Ciul/angular-facebook#115]
Hi,
the module is working great! tank you very much!
but i didnt find example of how you request more permissions for the login of the application,
i would like  to request the user approve  'email','ads_management' permissions,
I beliebe it should be in the config :

function(FacebookProvider) {
    // Set your appId through the setAppId method or
    // use the shortcut in the initialize method directly.
    FacebookProvider.init('appId');
}

appreciate it
Alon

**Comment by pbassut** [comment]
I'm not so sure but I think you could send a second parameter to Facebook.login as an object and set the scope from there. Something like:

``` javascript
var callback_function = function(){};
Facebook.login(callback_function, {'scope': 'email,public_profile'});
```

**Comment by melody1798** [comment]
@pbassut . Thanks
