### ISSUE TITLE
net::ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by zeeshanjan82** [Ciul/angular-facebook#128]
I am getting net::ERR_BLOCKED_BY_CLIENT when putting following line in index.html

``` html
  <script src="http://connect.facebook.net/en_US/sdk.js"></script>
```

**Comment by johanssonmarcus** [comment]
Are you running AdBlockPlus or something similar?

**Comment by luiscarlosjayk** [comment]
No, it is not running that.
