### ISSUE TITLE
Facebook login callback not called

### ISSUE THREAD

**Issue by romainberger** [Ciul/angular-facebook#30]
Hi,

The login callback is never called the first time the user authorize the app, which forces the user to reload the page and re-click on the login button. Any idea how to make it work? The same issue happens in your demo. I also tried watching for the facebook events but none of them are happening.

``` javascript
$scope.login = function() {
    Facebook.login(function(response) {
        // this is never called ;_;
        if (response.status == 'connected') {
          // I need to do stuff here
        }
      }, {scope: 'email,user_birthday,user_likes'});
};
```

Thanks

**Comment by antidote2** [comment]
you might have stumped over this safari popup blocker issue as I did: 
http://stackoverflow.com/questions/26817023/fb-login-inside-fb-getloginstatus-popup-window-blocked
