### ISSUE TITLE
getLoginStatus hangs

### ISSUE THREAD

**Issue by atticoos** [Ciul/angular-facebook#49]
Using the example code in the readme, `Facebook.getLoginStatus(function(){})` never calls back..

Anyone else experiencing this issue?

**Comment by pbassut** [comment]
@chrisjowen thanks man. That was exactly my issue. You just saved my life.

**Comment by pbassut** [comment]
@chrisjowen My bad, it's still hanging. Anyone knows what could be the cause? I'm using a domain registered in my app config page. Still it's not working.

**Comment by pbassut** [comment]
Right, for people coming to this issue:
I had to go to [this](http://stackoverflow.com/questions/19098952/given-url-is-not-allowed-by-the-application-configuration-facebook-application-e?lq=1) answer on SO to find out that I had to add that too.
Also, test on a incognito instance of chrome to wipe out cookies and such.
