### ISSUE TITLE
[ie8] Problem with indexOf prototype

### ISSUE THREAD

**Issue by danielmouraa** [Ciul/angular-facebook#86]
I receive the error 'Object doesn't support this propety or method' at line 595 character 13.

I solved this problem adding this code: http://stackoverflow.com/questions/3629183/why-doesnt-indexof-work-on-an-array-ie8

**Comment by Ciul** [comment]
Oh great!, you should pull your solution then :)

Thanks & Regards

**Comment by mrzmyr** [comment]
Instead of adding this to the `angular-facbook` module, I recommend, just to add [the fix](http://stackoverflow.com/a/3629211/237209) to your project specific codebase.
