### ISSUE TITLE
How to access the FB Access Token and Store it in Database

### ISSUE THREAD

**Issue by Rajavasanthan** [Ciul/angular-facebook#88]
1. How can i Access the Facebook Access-Token and Store it in Database. I am using Laravel has my Back End.
2. I  have a Dash Board Route in my Angular App. I want to prevent that from Users who are not Logged in with FB. How can i do that with this Script?

**Comment by cedricsandars** [comment]
You will get FB access token in the login api itself.

         Facebook.login(function(response) {
          if (response.status == 'connected') {
            console.log('Access token,FB ID, etc'+JSON.stringify(response));
          }
