### ISSUE TITLE
Facebook login doesn't answer

### ISSUE THREAD

**Issue by MarcosPortugal** [Ciul/angular-facebook#93]
When I programatically call Facebook.login() (right after a click on a button, and the circumstances aren't very clear but I can dig them out if you need to know every aspect of this), the promise never gets concluded. I set up some console.logs on the angular-facebook source code, and put a "//" in front of the ones that execute. Can you figure anything out from this?

 http://imgur.com/9FEgDmJ

**Comment by Ciul** [comment]
Please create something that shows how you are using it at plnkr or jsfiddle.
Otherwise, I won't be able to help you.

Regards

**Comment by MarcosPortugal** [comment]
I have to go now, but I can work on that tomorrow morning. Thank you :) And pretty much I'm just calling Facebook.login() but the callback is never returned. Can't you get an idea of what's wrong by knowing the parts of the code that get called? (image posted above)

**Comment by Ciul** [comment]
Sorry but no. That doesn't show how are you setting the app and calling it.
I used last week the module, so I can tell you it works. But well, let's see tomorrow with your code. Not the module source code.

Regards

**Comment by MarcosPortugal** [comment]
Soo I found out what the problem was this morning. It's in portuguese but I think you can get what it's about :) 
![untitled](https://cloud.githubusercontent.com/assets/3464445/6479645/a0d8b466-c240-11e4-9c35-c4136bdf1a43.png)

**Comment by MarcosPortugal** [comment]
I'm guessing it's my code that takes too long to trigger the login after the button press. I'll see what I can do. Thank you for your time!

**Comment by Ciul** [comment]
That uses to happen when the login function is not called directly on an onclick (or other user) event, insted, called from script out of an user intervention. But there you go, if you place a plunker you could get more help from others :)

Regards
