### ISSUE TITLE
Is there a reason why NgFacebook.prototype.login() is separated from NgFacebook.prototype.['logout', 'api', 'ui', 'getLoginStatus'] definition ?

### ISSUE THREAD

**Issue by eightyfive** [Ciul/angular-facebook#98]
I was [reviewing the code](https://github.com/Ciul/angular-facebook/blob/master/lib/angular-facebook.js#L272) and these 2 prototype methods looks exactly the same.
I mean they are different only because login() is not taking advantage of loadDeferred promise.

Is there a reason for that?

**Comment by Ciul** [comment]
You seem to be right. The only difference might be the check for the isReady flag.
Thus, it could be that login method be mixed as well with others.
Could you send a pull request on it?
